networks:
    default:
        name: llm-rag-network
        external: true
services:
    text_processor:
        image: paper-with-data
        container_name: text_processor
        volumes:
            - ../secrets:/secrets
            - ${PWD}:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
        # command: sleep infinity

        # depends_on:
        #     - chromadb
    featureExtracter:
        image: paper-with-data
        container_name: featureExtracter
        volumes:
            - ../secrets:/secrets
            - ${PWD}:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
        # command: sleep infinity

    embedding:
        image: paper-with-data
        container_name: embedding
        volumes:
            - ../secrets:/secrets
            - ${PWD}:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
        # command: sleep infinity

    # chromadb:
    #     image: chromadb/chroma:latest
    #     container_name: llm-rag-chromadb
    #     ports:
    #         - 8000:8000
    #     volumes:
    #         - ./docker-volumes/chromadb:/chroma/chroma
    #     environment:
    #         - IS_PERSISTENT=TRUE
    #         - ANONYMIZED_TELEMETRY=FALSE
    #         - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.
