networks:
    default:
        name: llm-rag-network
        external: true

services:
    text_processor:
        build:
            context: ./text_processor
        container_name: text_processor
        volumes:
            - ../secrets:/secrets
            - ${PWD}/text_processor:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT

    featureextracter:  # Renamed to lowercase
        build:
            context: ./featureExtracter
        container_name: featureExtracter  # Renamed to lowercase
        volumes:
            - ../secrets:/secrets
            - ${PWD}/featureExtracter:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT

    rag:
        build:
            context: ./rag
        container_name: rag
        volumes:
            - ../secrets:/secrets
            - ${PWD}/rag:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
