name: CI and CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install black flake8

      - name: Reformat Code with Black
        run: |
          black .
      
      - name: Check Code Format with Black
        run: black --check .

      # - name: Lint Code with Flake8
      #   run: flake8 .

      # - name: Verify No Changes
      #   run: |
      #     if [ -n "$(git status --porcelain)" ]; then
      #       echo "There are uncommitted changes. Please commit or stash them before pushing."
      #       git diff
      #       exit 1
      #     fi

  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 3: Start Services with Docker Compose
      - name: Start Services
        run: sh ./src/docker-shell.sh

      # Step 4: Run Tests Inside text_processor Container with pipenv
      - name: Run Pytest in pipenv Environment
        run: |
          docker exec text_processor sh -c "
              pipenv run pytest --cov=text_processor --cov-report=term-missing
          "
        env:
          COVERAGE_FILE: /tmp/.coverage

      # Step 5: Stop Docker Compose Services
      - name: Stop Services
        run: docker compose down
      