name: CI and CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [windows-latest, macos-latest]
    # runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install black flake8

      - name: Check Code Format with Black
        run: black --check .

      - name: Lint Code with Flake8
        run: flake8 .

  test:
      runs-on: ubuntu-latest

      steps:
        # Step 1: Checkout the repository code
        - name: Checkout code
          uses: actions/checkout@v3

        # Step 2: Set up Python environment (specifically Python 3.12)
        - name: Set up Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        # Step 2.1: Set PYTHONPATH to include the root directory (or src if relevant)
        - name: Set PYTHONPATH
          run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV  # Adds current directory to PYTHONPATH


        # Step 3: Install pytest and pytest-cov for coverage
        - name: Install pytest and pytest-cov
          run: |
            pip install pytest pytest-cov

        # Step 4: Run pytest with coverage and generate HTML report
        - name: Run tests with coverage
          run: |
            pytest --cov=. --cov-report=html

        # Step 5: Upload coverage report as an artifact
        - name: Upload coverage report
          uses: actions/upload-artifact@v3
          with:
            name: coverage-report
            path: htmlcov  # The folder where pytest-cov stores HTML reports
